/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetp4;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author adrie
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    Joueur[] ListeJoueurs = new Joueur[2];
    Joueur joueurCourant;
    Grille grilleJeu = new Grille();

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        panneau_info_joueurs.setVisible(false);
        paneau_info_partie.setVisible(false);

        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.CelluleJeu[i][j]);
                panneau_grille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        paneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_info_joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        lbl_j1_desint = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        lbl_j2_couleur = new javax.swing.JLabel();
        lbl_j2_desint = new javax.swing.JLabel();
        paneau_info_partie = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        javax.swing.JButton btl_col_0 = new javax.swing.JButton();
        btl_col_1 = new javax.swing.JButton();
        btl_col_2 = new javax.swing.JButton();
        btl_col_3 = new javax.swing.JButton();
        btl_col_4 = new javax.swing.JButton();
        btl_col_5 = new javax.swing.JButton();
        btl_col_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 672, 576));
        panneau_grille.getAccessibleContext().setAccessibleName("");

        paneau_creation_partie.setBackground(new java.awt.Color(255, 0, 51));
        paneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur 1:");
        paneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, -1));

        jLabel2.setText("Nom joueur 2 : ");
        paneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        nom_joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur1ActionPerformed(evt);
            }
        });
        paneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));
        paneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 90, -1));

        btn_start.setText("Demarrer partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        paneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        getContentPane().add(paneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 330, 180));

        panneau_info_joueurs.setBackground(new java.awt.Color(51, 51, 255));
        panneau_info_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("infos joueurs");
        panneau_info_joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel4.setText("couleur");
        panneau_info_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel5.setText("joueur 1");
        panneau_info_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setText("desintegrateurs");
        panneau_info_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lbl_j1_nom.setText("nomjoueur1");
        panneau_info_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, -1));

        lbl_j1_couleur.setText("couleurjoueur1");
        panneau_info_joueurs.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, -1));

        lbl_j1_desint.setText("nbdesintegrateur1");
        panneau_info_joueurs.add(lbl_j1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, -1));
        panneau_info_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));
        panneau_info_joueurs.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 280, 0));
        panneau_info_joueurs.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 270, -1));

        jLabel7.setText("couleur");
        panneau_info_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel8.setText("joueur 2");
        panneau_info_joueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel9.setText("desintegrateurs");
        panneau_info_joueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lbl_j2_nom.setText("nomjoueur2");
        panneau_info_joueurs.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        lbl_j2_couleur.setText("couleurjoueur2");
        panneau_info_joueurs.add(lbl_j2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        lbl_j2_desint.setText("nbdesintegrateur2");
        panneau_info_joueurs.add(lbl_j2_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        getContentPane().add(panneau_info_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 330, 250));

        paneau_info_partie.setBackground(new java.awt.Color(51, 204, 0));
        paneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("infos jeu");
        paneau_info_partie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel11.setText("joueur courant");
        paneau_info_partie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lbl_jcourant.setText("nom joueur");
        paneau_info_partie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        paneau_info_partie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, -1));

        getContentPane().add(paneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 330, 180));

        btl_col_0.setText("1");
        btl_col_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btl_col_1.setText("2");
        btl_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 40, -1, -1));

        btl_col_2.setText("3");
        btl_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 40, -1, -1));

        btl_col_3.setText("4");
        btl_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 40, -1, -1));

        btl_col_4.setText("5");
        btl_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 40, -1, -1));

        btl_col_5.setText("6");
        btl_col_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        btl_col_6.setText("7");
        btl_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btl_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btl_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 40, -1, -1));

        setBounds(0, 0, 1106, 732);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_info_joueurs.setVisible(true);
        paneau_info_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    private void nom_joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur1ActionPerformed

    private void btl_col_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_0ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(0);
    }//GEN-LAST:event_btl_col_0ActionPerformed

    private void btl_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_1ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(1);
    }//GEN-LAST:event_btl_col_1ActionPerformed

    private void btl_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_2ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(2);
    }//GEN-LAST:event_btl_col_2ActionPerformed

    private void btl_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_3ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(3);
    }//GEN-LAST:event_btl_col_3ActionPerformed

    private void btl_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_4ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(4);
    }//GEN-LAST:event_btl_col_4ActionPerformed

    private void btl_col_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_5ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(5);
    }//GEN-LAST:event_btl_col_5ActionPerformed

    private void btl_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btl_col_6ActionPerformed
        joueurSuivant();// TODO add your handling code here:
        jouerDansColonne(6);
    }//GEN-LAST:event_btl_col_6ActionPerformed
    
    public boolean jouerDansColonne(int indice_colonne){
        boolean resultatAction;
        resultatAction  = grilleJeu.ajouterJetonDansColonne(joueurCourant.ListeJetons[joueurCourant.nombreJetonsRestants - 1], indice_colonne);
        joueurCourant.ListeJetons[joueurCourant.nombreJetonsRestants] = null;
        panneau_grille.repaint();
        return true;
    }
    
    public void joueurSuivant(){
        if (joueurCourant == ListeJoueurs[0]){
            joueurCourant = ListeJoueurs[1];
        }
        else{
            joueurCourant = ListeJoueurs[0];
        }
        lbl_jcourant.setText(joueurCourant.nom);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    public void initialiserPartie(){

        String nomfct1 = nom_joueur1.getText();
        Joueur Nomj1 = new Joueur(nomfct1);
        String nomfct2 = nom_joueur2.getText();
        Joueur Nomj2 = new Joueur(nomfct2);
        System.out.println(nomfct1 + nomfct2);
        Random ltnDs = new Random();
        int lignetnDs = ltnDs.nextInt(5) ;
        Random ctnDs = new Random();
        int colonnetnDs = ctnDs.nextInt(6) ;
        grilleJeu.placerTrouNoir(lignetnDs, colonnetnDs);
        grilleJeu.placerDesintegrateur(lignetnDs, colonnetnDs);
        panneau_grille.repaint();
        ListeJoueurs[0] = Nomj1;
        ListeJoueurs[1] = Nomj2;
        
        System.out.print(ListeJoueurs[0]);
        
        Random ltnDs2 = new Random();
        int lignetnDs2 = ltnDs2.nextInt(5) ;
        Random ctnDs2 = new Random();
        int colonnetnDs2 = ctnDs2.nextInt(6) ;
        grilleJeu.placerTrouNoir(lignetnDs2, colonnetnDs2);
        grilleJeu.placerDesintegrateur(lignetnDs2, colonnetnDs2);
        panneau_grille.repaint();
        
        for (int i = 0 ;i <= 2; i++){
            
            Random tn = new Random();
            
            int lignetn = tn.nextInt(5) ;

            int colonnetn = tn.nextInt(6) ;
            
            while(grilleJeu.CelluleJeu[lignetn][colonnetn].presenceTrouNoir()==true){
               
                lignetn = tn.nextInt(5) ;

                colonnetn = tn.nextInt(6) ;
            }
           
            grilleJeu.placerTrouNoir(lignetn, colonnetn);

        }    
        panneau_grille.repaint();
        for (int i = 0 ;i <= 2; i++){

            Random ds = new Random();

            int ligneds = ds.nextInt(5) ;

            int colonneds = ds.nextInt(6) ;
            
            while(grilleJeu.CelluleJeu[ligneds][colonneds].presenceDesintegrateur()==true){
               
                ligneds = ds.nextInt(5) ;

                colonneds = ds.nextInt(6) ;
            }

            grilleJeu.placerDesintegrateur(ligneds, colonneds);
            
        }
        panneau_grille.repaint();
        attribuerCouleursAuxJoueurs();
        System.out.println(ListeJoueurs[0].couleur);
        
        for(int i=0; i<21 ; i++){

           ListeJoueurs[0].ListeJetons[i] = new Jeton(ListeJoueurs[0].couleur);

           ListeJoueurs[1].ListeJetons[i] = new Jeton(ListeJoueurs[1].couleur);

        }     
        
        lbl_j1_nom.setText(nomfct1);
        lbl_j2_nom.setText(nomfct2);
        lbl_j1_couleur.setText(ListeJoueurs[0].couleur);
        lbl_j2_couleur.setText(ListeJoueurs[1].couleur);
        lbl_j2_desint.setText(ListeJoueurs[1].nombreDesintegrateurs+"");
        lbl_j1_desint.setText(ListeJoueurs[0].nombreDesintegrateurs+"");
        panneau_info_joueurs.repaint();
        panneau_grille.repaint();
        
        Random rn = new Random();
        int jdep = rn.nextInt(1) ;
        if (jdep == 0){
           joueurCourant = ListeJoueurs[0];
        }
        if (jdep == 1){
           joueurCourant = ListeJoueurs[1];
        }
        
        lbl_jcourant.setText(joueurCourant.nom);
        panneau_grille.repaint();


    }
    public void attribuerCouleursAuxJoueurs(){
        Random rn = new Random();
        int temp = rn.nextInt(2) ;
        if (temp == 1){
            ListeJoueurs[0].couleur = "rouge";
            ListeJoueurs[1].couleur = "jaune";
        }
        if (temp==0){
            ListeJoueurs[0].couleur = "jaune";
            ListeJoueurs[1].couleur = "rouge";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btl_col_1;
    private javax.swing.JButton btl_col_2;
    private javax.swing.JButton btl_col_3;
    private javax.swing.JButton btl_col_4;
    private javax.swing.JButton btl_col_5;
    private javax.swing.JButton btl_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desint;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_couleur;
    private javax.swing.JLabel lbl_j2_desint;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel paneau_creation_partie;
    private javax.swing.JPanel paneau_info_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueurs;
    // End of variables declaration//GEN-END:variables
}
